### ISSUE TITLE
Adding positivity constraints change the result

### ISSUE THREAD

**Issue by stla** [rasheedja/simplex-haskell#12]
Hello, 

I have these constraints:
```haskell
[LEQ {lhs = fromList [(1,1 % 1),(2,1 % 1),(3,0 % 1)], rhs = 1 % 1},LEQ {lhs = fromList [(1,1 % 1),(2,0 % 1),(3,1 % 1)], rhs = 1 % 1}]
```
and the objective is to maximize the first variable.

I get this result:
```haskell
Just (Result {objectiveVar = 6, varValMap = fromList [(1,1 % 1),(6,1 % 1)]})
```
Variables `2` and `3` do not appear in this resut.

Now I add the constraints "variable 2 positive" and "variable 3 positive":
```haskell
[LEQ {lhs = fromList [(1,1 % 1),(2,1 % 1),(3,0 % 1)], rhs = 1 % 1},LEQ {lhs = fromList [(1,1 % 1),(2,(-1) % 1),(3,0 % 1)], rhs = 0 % 1},LEQ {lhs = fromList [(1,1 % 1),(2,0 % 1),(3,(-1) % 1)], rhs = 0 % 1},LEQ {lhs = fromList [(1,1 % 1),(2,0 % 1),(3,1 % 1)], rhs = 1 % 1}]
```
Then I get the expected results, with variables `2` and `3` present this time:
```haskell
Just (Result {objectiveVar = 8, varValMap = fromList [(1,1 % 2),(2,1 % 2),(3,1 % 2),(8,1 % 2)]})
```
Is it normal? That sounds strange to me, because the positivity constraints should be implicit, no?

**Comment by stla** [comment]
Sorry, confusion... I didn't add `var2 > 0, var3 >0`, I added `var1 - var2 < 0, var1 - var3 < 0`.

But what does that mean when there are missing variables in the solution?

**Comment by stla** [comment]
I compared with another software, and I observed that each time I get some missing variables in the solution, then their value should be `0`.

**Comment by rasheedja** [comment]
> I compared with another software, and I observed that each time I get some missing variables in the solution, then their value should be `0`.

Yeah, sorry for not replying earlier.

Currently working on refactoring this anyway. Will take this into account

**Comment by rasheedja** [comment]
(And yeah, the positivity constraint should be implicit)
