### ISSUE TITLE
Unexpected results for simple (degenerate) cases

### ISSUE THREAD

**Issue by dylex** [rasheedja/simplex-haskell#8]
Thanks for this, it's quite useful and seems to work in most cases, but there are some weird results I don't quite understand.  Here's some things that work as expected:

- minimize x st x>=0, `twoPhaseSimplex (Min [(1,1)]) [GEQ [(1,1)] 0)`: correct 0
- maximize x st x>=0, `twoPhaseSimplex (Max [(1,1)]) [GEQ [(1,1)] 0)`: correct Nothing
- maximize -x st x>=0, `twoPhaseSimplex (Max [(1,-1)]) [GEQ [(1,1)] 0)`: correct 0
- minimize -x st x>=0, `twoPhaseSimplex (Min [(1,-1)]) [GEQ [(1,1)] 0)`: correct Nothing

But if I flip the constraint, either by using LEQ or negating it, the unbounded cases seem to fail:

- maximize x st x<=0, `twoPhaseSimplex (Max [(1,1)]) [LEQ [(1,1)] 0)`: correct 0
- minimize x st x<=0, `twoPhaseSimplex (Min [(1,1)]) [LEQ [(1,1)] 0)`: *incorrect* 0
- maximize -x st x<=0, `twoPhaseSimplex (Max [(1,-1)]) [LEQ [(1,1)] 0)`: *incorrect* 0
- minimize x st -x>=0, `twoPhaseSimplex (Min [(1,1)]) [GEQ [(1,-1)] 0)`: *incorrect* 0

Am I doing something wrong or misinterpreting something? I can reproduce this with various multiple varibles as well, but it only seems to happen when I'm essentially saying to minimize variables that are bounded above (rather than below).

**Comment by dylex** [comment]
Oh, I realized maybe there is an implicit assumption that all variables are non-negative, so solutions are always in the positive quadrant.  Is that the case?  I know the docs say "only use positive Integer variables" but I assumed that was referring to the variable labels/identifiers, not their values.

**Comment by dylex** [comment]
On further reading I realized this is a standard assumption of simplex in canonical form. The previous library I was using (not haskell) did not assume this. Sorry to bother.

**Comment by rasheedja** [comment]
No problem.

Yeah, you're right. There is an implicit assumption that each variable is `>= 0`.

> I know the docs say "only use positive Integer variables" but I assumed that was referring to the variable labels/identifiers, not their values.

I guess both are true in this case :D. The text here specifically refers to variable identifiers. The variable identifiers must be positive. However, I'm currently working on a large refactor and one of the things I've changed allows the use of non-positive variable identifiers. I don't currently plan to get rid of the assumption that the value of all variables are `>= 0`, at least for the current refactor I'm working on.
